language: python

# python versions to use during the tests
python:
    - "3.8"

# command to install dependencies
install:
    - pip install pytest
    - pip install pytest-cov 
    - pip install coveralls
    - pip install -r requirements.txt

# command to run tests
script:
    - pytest --doctest-modules --cov=ckb --cov-report term-missing

branches:
  only:
   - main

notifications:
  email:
    recipients:
      - raphael.sourty@gmail.com
    on_success: always
    on_failure: always

after_success:
  - coveralls